name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build to the main directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build via NPM
        run: |
          npm ci && npm run build && cp -arf build/* .

      - name: Commit to build branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Build
          branch: build
          create_branch: true